/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import org.junit.Test;

import edu.curso.HelloWorld;

import static org.junit.Assert.*;

@SuppressWarnings("unused")
public class AppTest {
    @Test public void appHasAGreeting() {
        HelloWorld classUnderTest = new HelloWorld();
        assertTrue(true);
    }
}
